name: my-minimal-api-external-db-network
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    env_file:
      - ../.env # Carica le variabili d'ambiente dal file .env
    networks:
      - my-net # Collega alla rete esistente
      # Non serve forwardPorts qui perch√© la rete bridge gestisce la comunicazione interna

networks:
  my-net:
    external: true # Dice a Docker di usare la rete esistente invece di crearne una nuova
